[package]
name = "rust-crypto-trader"
version = "0.1.0"
authors = ["Tobin C. Harding <tobin@coblox.tech>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
reqwest = "0.10"
serde_json = "1.0"
spectral = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "time", "macros", "sync"] }
