edition = "2018"
condense_wildcard_suffixes = true
format_macro_matchers = true
merge_imports = true
use_field_init_shorthand = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
overflow_delimited_expr = true
